### ISSUE TITLE
help wanted

### ISSUE THREAD

**Issue by NikitiyMMM** [perkss/c-kafka-examples#3]
Hello. Do you have some examples of using producer and consumer (how to create exact) from your code? It would be very helpful if you show some of examples.

**Comment by perkss** [comment]
Hi @NikitiyMMM yes if you check the library project https://github.com/perkss/c-kafka-examples/blob/main/LibProject/src/consumer.c#L8 and the https://github.com/perkss/c-kafka-examples/blob/main/LibProject/src/producer.c#L4. 

Can look to make the README explain this clearer or feel free to update it yourself. 

Hope this helps.
